// <auto-generated />
using filmdesigners.at.Data;
using filmdesigners.at.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace filmdesigners.at.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180325175105_Guids")]
    partial class Guids
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("filmdesigners.at.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("filmdesigners.at.Models.Award", b =>
                {
                    b.Property<string>("AwardID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Category");

                    b.Property<DateTime>("Date");

                    b.Property<string>("JobID");

                    b.Property<string>("MemberID");

                    b.Property<string>("Name");

                    b.Property<string>("ProjectID");

                    b.HasKey("AwardID");

                    b.HasIndex("JobID");

                    b.HasIndex("MemberID");

                    b.HasIndex("ProjectID");

                    b.ToTable("Award");
                });

            modelBuilder.Entity("filmdesigners.at.Models.Chapter", b =>
                {
                    b.Property<string>("ChapterID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("Edited");

                    b.Property<string>("Heading");

                    b.Property<string>("Page");

                    b.Property<string>("Text");

                    b.HasKey("ChapterID");

                    b.ToTable("Chapter");
                });

            modelBuilder.Entity("filmdesigners.at.Models.Enrollment", b =>
                {
                    b.Property<string>("EnrollmentID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("JobId");

                    b.Property<string>("MemberID");

                    b.Property<string>("ProjectID");

                    b.HasKey("EnrollmentID");

                    b.HasIndex("JobId");

                    b.HasIndex("MemberID");

                    b.HasIndex("ProjectID");

                    b.ToTable("Enrollment");
                });

            modelBuilder.Entity("filmdesigners.at.Models.Event", b =>
                {
                    b.Property<string>("EventID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Picture");

                    b.Property<string>("Teaser");

                    b.Property<string>("Text");

                    b.Property<string>("Title");

                    b.HasKey("EventID");

                    b.ToTable("Event");
                });

            modelBuilder.Entity("filmdesigners.at.Models.Job", b =>
                {
                    b.Property<string>("JobId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<bool>("isPartner");

                    b.HasKey("JobId");

                    b.ToTable("Job");
                });

            modelBuilder.Entity("filmdesigners.at.Models.Member", b =>
                {
                    b.Property<string>("MemberId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("Activities");

                    b.Property<string>("Awards");

                    b.Property<DateTime>("Birthday");

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<DateTime>("Deathday");

                    b.Property<string>("EMail");

                    b.Property<string>("Education");

                    b.Property<string>("Fax");

                    b.Property<string>("Galleries");

                    b.Property<string>("InternationalExperiences");

                    b.Property<string>("JobId");

                    b.Property<string>("Languages");

                    b.Property<DateTime>("LastUpdate");

                    b.Property<bool>("Locked");

                    b.Property<bool>("Male");

                    b.Property<string>("Mobile");

                    b.Property<string>("Name");

                    b.Property<string>("Notes");

                    b.Property<string>("OtherContact");

                    b.Property<string>("OwnerID");

                    b.Property<bool>("Paused");

                    b.Property<string>("Phone");

                    b.Property<string>("Picture");

                    b.Property<bool>("Resigned");

                    b.Property<int>("Status");

                    b.Property<string>("Street");

                    b.Property<string>("Website");

                    b.Property<int>("ZIP");

                    b.HasKey("MemberId");

                    b.HasIndex("JobId");

                    b.ToTable("Member");
                });

            modelBuilder.Entity("filmdesigners.at.Models.Project", b =>
                {
                    b.Property<string>("ProjectID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Countries");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Link");

                    b.Property<string>("Name");

                    b.Property<string>("OwnerID");

                    b.Property<string>("Production");

                    b.Property<string>("Regiesseur");

                    b.Property<int>("Type");

                    b.HasKey("ProjectID");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("filmdesigners.at.Models.Award", b =>
                {
                    b.HasOne("filmdesigners.at.Models.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobID");

                    b.HasOne("filmdesigners.at.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberID");

                    b.HasOne("filmdesigners.at.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectID");
                });

            modelBuilder.Entity("filmdesigners.at.Models.Enrollment", b =>
                {
                    b.HasOne("filmdesigners.at.Models.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId");

                    b.HasOne("filmdesigners.at.Models.Member", "Member")
                        .WithMany("Enrollments")
                        .HasForeignKey("MemberID");

                    b.HasOne("filmdesigners.at.Models.Project", "Project")
                        .WithMany("Enrollments")
                        .HasForeignKey("ProjectID");
                });

            modelBuilder.Entity("filmdesigners.at.Models.Member", b =>
                {
                    b.HasOne("filmdesigners.at.Models.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("filmdesigners.at.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("filmdesigners.at.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("filmdesigners.at.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("filmdesigners.at.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
